import daisyui from 'daisyui';

// Oracle Redwood-inspired semantic tokens. Keep component markup theme-agnostic.

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Oracle Sans', 'Oracle Sans UI', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica Neue', 'Arial', 'sans-serif'],
        serif: ['Georgia', 'Times New Roman', 'serif'],
      },
      boxShadow: {
        redwood: '0 2px 4px -2px rgb(0 0 0 / 0.10)',
        'redwood-lg': '0 0.5rem 2rem -10px rgb(0 0 0 / 0.30)',
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        light: {
          primary: '#315357',
          'primary-content': '#FFFFFF',
          secondary: '#697778',
          'secondary-content': '#FFFFFF',
          accent: '#C74634',
          'accent-content': '#FFFFFF',
          neutral: '#1E3133',
          'neutral-content': '#F8F7F5',
          'base-100': '#FCFBFA',
          'base-200': '#F1EFED',
          'base-300': '#D8D3CF',
          'base-content': '#262323',
          info: '#4F7D7B',
          'info-content': '#FFFFFF',
          success: '#3D7754',
          'success-content': '#FFFFFF',
          warning: '#A35D00',
          'warning-content': '#FFFFFF',
          error: '#B33A2B',
          'error-content': '#FFFFFF',
          '--rounded-box': '0.5rem',
          '--rounded-btn': '0.25rem',
          '--rounded-badge': '0.375rem',
          '--animation-btn': '0.18s',
          '--animation-input': '0.18s',
          '--btn-focus-scale': '0.99',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.25rem',
        },
      },
      {
        dark: {
          primary: '#8FB8B6',
          'primary-content': '#152526',
          secondary: '#AEBDBD',
          'secondary-content': '#152526',
          accent: '#F08A78',
          'accent-content': '#271512',
          neutral: '#172728',
          'neutral-content': '#F5F2EF',
          'base-100': '#202526',
          'base-200': '#171B1C',
          'base-300': '#3C4545',
          'base-content': '#F1EFED',
          info: '#86B4B1',
          'info-content': '#132323',
          success: '#80B790',
          'success-content': '#102318',
          warning: '#E4B35A',
          'warning-content': '#2C1D05',
          error: '#F08A78',
          'error-content': '#2B1310',
          '--rounded-box': '0.5rem',
          '--rounded-btn': '0.25rem',
          '--rounded-badge': '0.375rem',
          '--animation-btn': '0.18s',
          '--animation-input': '0.18s',
          '--btn-focus-scale': '0.99',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.25rem',
        },
      },
    ],
    darkTheme: 'dark',
    base: true,
    styled: true,
    utils: true,
  },
};
